export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_PENDING = 'LOAD_ITEMS_PENDING';
export const LOAD_ITEMS_FULFILLED = 'LOAD_ITEMS_FULFILLED';
export const LOAD_ITEMS_REJECTED = 'LOAD_ITEMS_REJECTED';

export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_FULFILLED = 'UPDATE_ITEM_FULFILLED';
export const UPDATE_ITEM_REJECTED = 'UPDATE_ITEM_REJECTED';

export const LOAD_MONEY = 'LOAD_MONEY';
export const LOAD_MONEY_PENDING = 'LOAD_MONEY_PENDING';
export const LOAD_MONEY_FULFILLED = 'LOAD_MONEY_FULFILLED';
export const LOAD_MONEY_REJECTED = 'LOAD_MONEY_REJECTED';

export const UPDATE_MONEY = 'UPDATE_MONEY';
export const UPDATE_MONEY_PENDING = 'UPDATE_MONEY_PENDING';
export const UPDATE_MONEY_FULFILLED = 'UPDATE_MONEY_FULFILLED';
export const UPDATE_MONEY_REJECTED = 'UPDATE_MONEY_REJECTED';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
