export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const SELECT_ITEM_SUCCESS = 'SELECT_ITEM_SUCCESS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';

export const UPDATE_MONEY_SUCCESS = 'UPDATE_MONEY_SUCCESS';
export const LOAD_MONEY_SUCCESS = 'LOAD_MONEY_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
